### PR TITLE
On November 13, 2020 username and password authentication to the REST API and the OAuth Authorizations API were deprecated and no longer work.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery can you send me a follow up pull?

Still very big

```
EQUEST 94703 - LPS-119446 (liferay-continuous-integration)
	https://github.com/brianchandotcom/liferay-portal/pull/94703
	Forwarded from: https://github.com/hhuijser/liferay-portal/pull/4917 (Took 2
	`ci:forward` attempts in 10 hours 18 minutes)

	@hhuijser



	:heavy_check_mark: ci:test:stable - 20 out of 20 jobs
	passed:heavy_check_mark: ci:test:relevant - 60 out of 63 jobs passed
	in 2 hours 32 minutesClick here for more
	details.Base Branch:Branch Name: master
	Branch GIT ID: f193301b2848899b008d51513af62a3b3a9b7888Copied in Private Modules Branch:Branch Name: master-
	private
	Branch GIT ID: 13c59df02738cba7c7387b3490775720676498c7
	ci:test:stable - 20 out of 20 jobs
	PASSED20 Successful
	Jobs:test-portal-
	acceptance-pullrequest-batch(master)/functional-smoke-
	tomcat90-mysql57-jdk8_stable/0test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/1test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/10test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/11test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/2test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/3test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/4test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/5test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/6test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/7test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/8test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/9test-portal-acceptance-pullrequest-batch(master)/js-
	unit-jdk8test-portal-acceptance-
	pullrequest-batch(master)/modules-integration-
	mysql57-jdk8_stabletest-portal-acceptance-
	pullrequest-batch(master)/modules-unit-jdk8_stabletest-portal-acceptance-pullrequest-batch(master)/pmd-
	jdk8test-portal-acceptance-
	pullrequest-batch(master)/rest-builder-jdk8test-portal-acceptance-pullrequest-batch(master
	)/service-builder-jdk8test-portal-
	acceptance-pullrequest-batch(master)/unit-jdk8_stableci:test:relevant - 59 out of 63 jobs
	PASSED4 Failed Jobs:test-portal-acceptance-
	pullrequest(master)test-portal-acceptance-pullrequest-
	batch(master)/functional-
	tomcat90-mysql57-jdk8/1test-portal-acceptance-pullrequest-
	batch(master)/functional-
	tomcat90-mysql57-jdk8/2test-portal-acceptance-pullrequest-
	batch(master)/functional-tomcat90-mysql57-jdk8/359 Successful
	Jobs:test-portal-
	acceptance-pullrequest-batch(master)/central-requirements-jdk8test-portal-acceptance-pullrequest-batch(master
	)/functional-smoke-tomcat90-mysql57-jdk11_open/0test-portal-acceptance-pullrequest-batch(master
	)/functional-smoke-tomcat90-mysql57-jdk8_stable/0test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/0test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/10test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/11test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/12test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/13test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/14test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/15test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/16test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/17test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/18test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/19test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/4test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/5test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/6test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/7test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/8test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/9test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/0test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/1test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/10test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/11test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/2test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/3test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/4test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/5test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/6test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/7test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/8test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8/9test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/1test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/10test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/11test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/2test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/3test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/4test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/5test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/6test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/7test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/8test-portal-acceptance-pullrequest-batch(master
	)/functional-upgrade-tomcat90-mysql57-jdk8_stable/9test-portal-acceptance-pullrequest-batch(master)/js-
	unit-jdk8test-portal-acceptance-
	pullrequest-batch(master)/lpkg-base-jdk8test-portal-acceptance-pullrequest-batch(master)/lpkg-
	controller-jdk8test-portal-acceptance-
	pullrequest-batch(master)/modules-compile-jdk8test-portal-acceptance-pullrequest-batch(master
	)/modules-integration-mysql57-jdk8test-portal-acceptance-pullrequest-batch(master
	)/modules-integration-mysql57-jdk8_stabletest-portal-acceptance-pullrequest-batch(master
	)/modules-semantic-versioning-jdk8test-portal-acceptance-pullrequest-batch(master
	)/modules-unit-jdk8test-portal-acceptance-
	pullrequest-batch(master)/modules-unit-jdk8_stabletest-portal-acceptance-pullrequest-batch(master)/pmd-
	jdk8test-portal-acceptance-
	pullrequest-batch(master)/rest-builder-jdk8test-portal-acceptance-pullrequest-batch(master
	)/semantic-versioning-jdk8test-portal-acceptance-pullrequest-batch(master
	)/service-builder-jdk8test-portal-
	acceptance-pullrequest-batch(master)/unit-jdk8test-portal-acceptance-pullrequest-batch(master)/unit-
	jdk8_stableFor more details click here.This pull contains no unique
	failures.Failures in common with acceptance upstream results at
	f193301b2848899b008d51513af62a3b3a9b7888:test-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/1Job Results:18
	Tests Passed.
	1 Test Failed.AXIS_VARIABLE=0,label_exp=!master
	#361755LocalFile.AssetPubl
	isherWithWebContent#ViewWebContentViaAPAsGuestWithViewPermission - Poshi Report - Poshi Summary - Console
	Outputtest-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/2Job Results:17
	Tests Passed.
	1 Test Failed.AXIS_VARIABLE=0,label_exp=!master
	#408257LocalFile.WebContentExpo
	rtImport#AddWebContentFromImportedStructureAndTemplate - Poshi Report - 
	Poshi Summary - Console
	Outputtest-portal-acceptance-pullrequest-batch(master
	)/functional-tomcat90-mysql57-jdk8/3Job Results:1
	Test Passed.
	1 Test Failed.AXIS_VARIABLE=0,label_exp=!master
	#447613LocalFile.WebContentW
	ithPermissions#AddAndViewStructureAndTemplateWithPermissions - Poshi Report - Poshi Summary - Console Output


	:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3
	minutesClick here for more details.Base
	Branch:Branch Name: master
	Branch GIT ID: f193301b2848899b008d51513af62a3b3a9b7888Sender Branch:Branch Name: LPS-119446
	Branch GIT ID: 9bcdea56f336f481f60a4f1fd6edf4c8b31981d71 out of 1jobs PASSED1 Successful
	Jobs:test-portal-source-
	formatFor more details click here.

```

But more readable than before.

I think we should keep the first X characters.

**Comment by brianchandotcom** [comment]
@inacionery also, when I run "git merge"

It throws this error now:

```
Closing pull request
Could not authorize you to connect with Github.
```

So I reverted this for now f3e7a5a4c219102f1bcf110e3065a7476281c3d4

**Comment by inacionery** [comment]
taking a look

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/git-tools/pull/3

**Pull request closed without merging**
