### PR TITLE
Add a line limit to the description

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/git-tools/compare/f3e7a5a4c2...e307b5f519

**Comment by brianchandotcom** [comment]
@inacionery can you make it so if I set

description-char-limit to 0, then it doesn't show the description at all? and without ...

Thx.

**Comment by inacionery** [comment]
Sure!

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/git-tools/pull/4

**Pull request closed without merging**
